### PR TITLE
Implemented:  Delay Calculator (Calculating Propagation Delay) #396 

### PR DESCRIPTION
**Pull request by sikehish**
### Issue Id you have worked upon - 
[ Delay Calculator (Calculating Propagation Delay) #396 ](https://github.com/SarthakKeshari/calc_for_everything/issues/396)

### Briefly explain your program logic - 
I'm using three textfields namely - speed, distance and delay. I take 2 of these values and compute. Im also throwing errors whenever the given input cannot be parsed into a float value(or is NaN).

### Screenshots(Attach 2 screenshots of your own input and output) - 
In the video below, I show the working of the calculator.
https://github.com/SarthakKeshari/calc_for_everything/assets/90673701/09112e60-7f6e-4c2b-ac21-20e7737aec85

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @sikehish on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by SarthakKeshari** [comment]
@sikehish,
Very well written code and implementation. Adding admin-appreciation points for the efforts put in. 👏👏

**Comment by sikehish** [comment]
> @sikehish, Very well written code and implementation. Adding admin-appreciation points for the efforts put in. 👏👏

Thank you so much @SarthakKeshari! Means a lot :))

**Pull request merged**
