### PR TITLE
Added median calculator

### PR DESCRIPTION
**Pull request by Rishika631**
### Issue Id you have worked upon - 
#448

### Briefly explain your program logic - 

Data Preparation: Start with input data, including either value ranges or individual data points with their frequencies.
Cumulative Frequency: If cumulative frequency is selected, determine the median by identifying the point where the cumulative frequency crosses half of the total.
Non-Cumulative Frequency: If not using cumulative frequency, create an array of values within the range or individual values.
Data Sorting: Sort the data in ascending order to find the middle values.
Median Calculation: Compute the median by averaging the two middle values for even-sized datasets or selecting the middle value for odd-sized datasets.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Rishika631,
Kindly revert the changes made to file - calculators/src/mathematical/homogeneousInterpreter/MainHomogeneousInterpreter.js

**Comment by SarthakKeshari** [comment]
@Rishika631,
Kindly do not delete the file as it will impact the project. Just revert the changes in the file.

**Comment by Rishika631** [comment]
@SarthakKeshari Yeah I didnot delete it. I am new to open source so can you please tell me how to revert back the file. I tried deleting all the changes made in homogeneous calc file in this pull request but I am not sure if it worked.

**Comment by Rishika631** [comment]
@SarthakKeshari should I close this pull request and make a new one instead?

**Comment by Rishika631** [comment]
@SarthakKeshari now check it once I have updated the branch so now it won't affect homogeneous interpreter file

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@Rishika631,
I appreciate the efforts you have put in to figure out how to revert the files and update this PR. As well as you have added the correct file, and the PR looks healthy. Thank you for your time and effort. I wish to appreciate this effort by adding admin-appreciation to this PR.

Keep learning. Wish you the best in your learning journey.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Rishika631 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by Rishika631** [comment]
Thank you so much. I am really thankful for this. Can you also please tell me your discord id where I can connect with you if I have an issue please.

**Comment by SarthakKeshari** [comment]
@Rishika631, 
I am not an active discord user, I would be glad to connect on LinkedIn - https://www.linkedin.com/in/sarthak-keshari

**Pull request merged**
