### PR TITLE
#443 Added UI + Logic

### PR DESCRIPTION
**Pull request by IshaanShettigar**
### Issue Id you have worked upon - 
#443 

### Briefly explain your program logic - 
Created 3 `TextField`s, and assigned 3 normal state variables for each as well as an error state variable for each `TextField`. The error is set to true if the user types something that is not a number, which then changes the UI appropriately. The Gravitational Force state is also changed appropriately.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image

image

image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @IshaanShettigar on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by SarthakKeshari** [comment]
@IshaanShettigar,
It's really impressive to see Material UI being used at its best. You have implemented couple of things in UI that I was expecting the participants to come up with. I really appreciate your understanding in UI and logic implementation. Adding admin-appreciation points for this PR. 👏👏

**Comment by IshaanShettigar** [comment]
Thank you so much, I really appreciate it!
@SarthakKeshari I noticed a small error where the Gravitational Force shows NaN N, instead of the error message, when the button is clicked once. (It shows the proper error message only when clicked twice). I apologize for this oversight, I'm new to React. I have since rectified this and improved the error UI. Now as soon as the user types in something that cannot be parsed, it shows the red error outline. To do it I used `useEffect`, shall I create a new PR and add these changes?

**Comment by SarthakKeshari** [comment]
> Thank you so much, I really appreciate it! @SarthakKeshari I noticed a small error where the Gravitational Force shows NaN N, instead of the error message, when the button is clicked once. (It shows the proper error message only when clicked twice). I apologize for this oversight, I'm new to React. I have since rectified this and improved the error UI. Now as soon as the user types in something that cannot be parsed, it shows the red error outline. To do it I used `useEffect`, shall I create a new PR and add these changes?

No worries, we'll take that up as bug resolution after Hacktoberfest

**Pull request merged**
