### PR TITLE
Body Fat Calculator

### PR DESCRIPTION
**Pull request by Saksham-245**
### Issue Id you have worked upon - 
#23 

### Briefly explain your program logic - 
- **State Variables** - The component uses React's useState hook to manage various state variables such as value, gender, age, weight, height, etc. These variables store the user's input and the calculated body fat percentage.
- **Unit Conversion:** - The value state variable is used to determine the unit system (US or Metric). If value is 0, the measurements are in US units and need to be converted to metric units for the calculation. This conversion is done inside the useEffect hook.
- **Body Fat Calculation:** -  The useEffect hook is also where the body fat percentage is calculated. The calculation is done using different formulas for males and females. The calculated body fat percentage is then stored in the bodyFat state variable.
- **Form Rendering:** -  The component renders a form where the user can input their gender, age, weight, height, neck, and waist measurements. The unit system can be toggled between US and Metric units using the Tabs component.
- **State Updates:** - The onChange handlers of the form inputs are used to update the corresponding state variables whenever the user inputs a value.
- **Result Display:** - The calculated body fat percentage is displayed at the bottom of the form. If the body fat percentage hasn't been calculated yet, 0 is displayed.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
Screenshot 2023-10-02 at 2 14 05 PM
Screenshot 2023-10-02 at 2 14 44 PM
<br>
### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Saksham-245, Glad to see that you have implemented both US Units as well as Metric Units.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Saksham-245 on your contribution.

**Comment by Saksham-245** [comment]
Thank You!! @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@Saksham-245,
I am revisiting this PR, as I wish to add appreciation points to your PR for not only giving best in implementing the logic but also explaining it so well.

Kudos to you!!

**Comment by Saksham-245** [comment]
Thank You @SarthakKeshari!!!👍🏻

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Pull request merged**
