### PR TITLE
This calculator group points which are on the same side of the line

### PR DESCRIPTION
**Pull request by Ayushlion8**
### Issue Id you have worked upon - 
Kindly write your answer here
 #86

### Briefly explain your program logic - 
Kindly write your answer here

Certainly, here's a brief overview of the program logic for the provided code:

1. **Initialization**: The code initializes state variables to manage the line, user-entered points, results, and input values for x and y.

2. **Function for Calculating Side**: A function calculates whether a point is on the same side, opposite side, or on the line based on its coordinates and the line's coordinates.

3. **Handling Line Input**: When users enter line points (x1, y1, x2, y2) and click the "Set Line" button, the function updates the line and visualizes it on a graph.

4. **Handling Point Input**: When users enter a point (x, y) and click the "Add Point" button, the function calculates the point's side with respect to the line, updates the list of points, and visually marks the point on the graph.

5. **Grouping Points**: Clicking the "Group Points" button filters the points into two groups: those on the same side of the line and those on the opposite side. These groups are displayed as results.

6. **Rendering**: The code provides a user interface with input fields for line and points, buttons for actions, displays results, and shows a dynamic graph below the input columns for a better user experience. The graph visualizes the line and marked points in real-time.

This code combines user interaction and logic to determine which side of a line points lie on, displaying the results both textually and graphically.

### A video of the working calculator - :

https://github.com/SarthakKeshari/calc_for_everything/assets/129222405/03244b62-11f7-4237-9e43-2b4c66e84f2f

### Screenshot

(Attach 2 screenshots of your own input and output) - 
Attach here:

Screenshot (137)
<br>

Screenshot (139)
<br>

Screenshot (138)
<br>

Screenshot (140)
<br>

Screenshot (141)
<br>

Screenshot (142)
<br>

### By raising this PR I affirm that -

- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Ayushlion8, 
Have exceeded the expectation 👏. Good job. Review may take a bit longer. You may go ahead and create more issues for time being.

Happy Contributing!! 🎉

**Comment by SarthakKeshari** [comment]
Considering the efforts, you have put in, upgrading issue status from easy -> medium 📈

**Comment by SarthakKeshari** [comment]
Hey @Ayushlion8,
I can see the use of external library - plotly.js and react-plotly.js. May you throw more light on these library as well as explain the advantage of using it.

**Comment by Ayushlion8** [comment]
> Hey @Ayushlion8, I can see the use of external library - plotly.js and react-plotly.js. May you throw more light on these library as well as explain the advantage of using it.

Yaa ofcourse @SarthakKeshari :)

Plotly.js and React-Plotly.js are JavaScript libraries used for creating interactive and visually appealing data visualizations and charts. Let's explore each of them and their advantages:

### Plotly.js:

Overview: Plotly.js is an open-source JavaScript graphing library that allows you to create interactive, web-based charts and data visualizations. It provides a wide range of chart types, including line charts, bar charts, scatter plots, pie charts, 3D plots, and more.

Advantages:

Interactive Visualizations: Plotly.js provides built-in interactivity features like zooming, panning, hovering, and tooltips, making it easy for users to explore data.

Wide Chart Variety: It supports a wide variety of chart types, allowing you to choose the best visualization for your data.

Customization: You can customize the appearance of charts, including colors, fonts, annotations, and more.

Dynamic Updates: Plotly.js can handle dynamic data updates, making it suitable for real-time data applications.

Use Cases:

Business Intelligence Dashboards
Data Analysis and Exploration
Real-time Monitoring and Analytics
Scientific Data Visualization


###React-Plotly.js:

Overview: React-Plotly.js is a React wrapper for Plotly.js. It integrates Plotly's capabilities into React applications seamlessly, allowing you to create and manage interactive charts using React components.

Advantages:

React Integration: React-Plotly.js is designed to work seamlessly with React, making it easy to incorporate interactive charts into React-based web applications.

Component-Based: Charts are created using React components, making it easy to manage and update chart elements as React state changes.

Reactivity: React-Plotly.js automatically updates charts when React state or props change, providing a reactive and responsive experience.

Props-Based Configuration: You can configure charts using React props, simplifying the process of passing data and settings to the chart components.

Use Cases:

React Web Applications
Single-Page Applications (SPAs)
Data Dashboards
Data Visualization in React Projects



In summary, Plotly.js and React-Plotly.js are powerful tools for creating interactive data visualizations. They offer flexibility, interactivity, and ease of use.

**Comment by Ayushlion8** [comment]
> Considering the efforts, you have put in, upgrading issue status from easy -> medium 📈

Thank you @SarthakKeshari :)

**Comment by SarthakKeshari** [comment]
@Ayushlion8,
Thanks for the explanation. 😊

**Comment by SarthakKeshari** [comment]
@Ayushlion8, 
Adding appreciation points for the dedication put in.

👏👏

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Ayushlion8 on your contribution.
Thanks for adding value to this repository. 😊

**Pull request merged**
