### PR TITLE
numerals calc added

### PR DESCRIPTION
**Pull request by plon-Susk7**
### Issue Id you have worked upon - 
#277 

### Briefly explain your program logic - 
I created a react component with useState hooks to update the placeholders. Used two libraries to convert number to words as there was no one standard library to do both Indian and International conversions.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by plon-Susk7** [comment]
Hi @SarthakKeshari, please review my PR. Thanks :)

**Comment by plon-Susk7** [comment]
Hi I made an update in Indian numeral column. I have fixed the rupees keyword.

image

**Review by SarthakKeshari — COMMENTED** [review]
Kindly place your Changes in MainNumeralToWords.js that is created.

And revert the changes in App.js and Home.js

**Comment by plon-Susk7** [comment]
I can't find path to MainNumeralToWords.js @SarthakKeshari.

**Comment by SarthakKeshari** [comment]
@plon-Susk7, Kindly check the issue comments #277

**Comment by plon-Susk7** [comment]
Made the necessary changes @SarthakKeshari. Thanks.

**Comment by SarthakKeshari** [comment]
@plon-Susk7,
1) Kindly delete the file - calculators/src/mathematical/numeralsToWords/InfoCI.js 
2) And revert the changes in App.js and Home.js

**Comment by plon-Susk7** [comment]
Done @SarthakKeshari. Thanks for the feedback :)

**Comment by plon-Susk7** [comment]
hi @SarthakKeshari , I believe that I made fork before you updated the repo so there are merge conflicts. Should I make another PR right now?

**Comment by SarthakKeshari** [comment]
Hi @plon-Susk7,
You may revert the last commit and take a pull, then again push your code.
If you are new to git kindly make a copy of you code, in case you may lose your file.
Any doubts then feel free to comment, I will help you out.

**Pull request closed without merging**
