### PR TITLE
Added Image to Text Reader

### PR DESCRIPTION
**Pull request by divyansh-4**
### Issue Id you have worked upon - 
#329 
### Briefly explain your program logic - 
Used Tesseract JS and buffer to enable users to upload a pdf with english text and get the extracted text in a text area.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by divyansh-4** [comment]
Hi @SarthakKeshari 
I accidentally closed the last pull request for this issue. Apologies for the inconvenience cause.
I have added the last code that you had approved. Do let me know incase changes are needed.
Thanks !

**Comment by SarthakKeshari** [comment]
@divyansh-4, No worries.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @divyansh-4 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Pull request merged**
