### PR TITLE
Feature/ashishnallana

### PR DESCRIPTION
**Pull request by ashishnallana**
### Issue Id you have worked upon - 
#451

### Briefly explain your program logic - 
I parsed user-provided grouped data from the table. The code finds the mode (the interval with the highest frequency), and displays "No mode" if there's no unique mode. It also alerts the user for empty input or incorrect data format.

### Screenshots(Attach 2 screenshots of your own input and output) - 
screenshot01
screenshot02

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@ashishnallana,
I bit of work is required at the UI end so that the input looks like this - 
Interval         |      Frequency   |   Cumulative Frequency
-------- | --------------- | ----------- 
0    -  10        |               5            |              5
10  -  20         |              3             |             8
20  -  30          |             8              |           16
...and so on and so forth.

**Comment by ashishnallana** [comment]
@SarthakKeshari I have made the changes you asked for, you can review it now.

**Comment by SarthakKeshari** [comment]
@ashishnallana,
You may autofill the cumulative frequency column. As per the frequency input by the user.

**Comment by ashishnallana** [comment]
@SarthakKeshari I have made the changes to autofill CF when frequency is entered. You can review now.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@ashishnallana,
Kindly revert App.js file.

**Comment by SarthakKeshari** [comment]
@ashishnallana, 
12 files have been altered kindly fix it.

**Comment by ashishnallana** [comment]
@SarthakKeshari I removed those 12 file alterations, but I am unable to revert App.js (The only thing changed in App.js is the ''=>"" and it happened because of my code formatter.)

**Comment by SarthakKeshari** [comment]
@ashishnallana,
I will take care of that.

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @ashishnallana on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
@ashishnallana,
Good UI. I appreciate the efforts you have put in to deliver this code. Adding admin-appreciation points to celebrate it. 👏👏

**Pull request merged**
