### PR TITLE
prefix , postfix to infix calculator

### PR DESCRIPTION
**Pull request by vendhan-ds**
### Issue Id you have worked upon - 
#120

### Briefly explain your program logic - 
This is a react component containing 3 textfields. User can input postfix and prefix expressions top obtain its infix expression.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
Kindly revert package-lock.json

**Comment by vendhan-ds** [comment]
sure, on it

**Comment by vendhan-ds** [comment]
@SarthakKeshari  yes, i have just reverted back package-lock.json file, thank you

**Comment by SarthakKeshari** [comment]
@vendhan-ds,
Kindly let me know the use of PostPreToIn.jsx file?

**Comment by vendhan-ds** [comment]
@SarthakKeshari as rightly pointed i have removed the unnecessary file, thaank you

**Comment by SarthakKeshari** [comment]
@vendhan-ds,
Thanks for making the required alterations in PR. I will review and merge the code.

**Comment by vendhan-ds** [comment]
thank you

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @vendhan-ds on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Pull request merged**
