### PR TITLE
Numerals to Words

### PR DESCRIPTION
**Pull request by plon-Susk7**
### Issue Id you have worked upon - 
https://github.com/SarthakKeshari/calc_for_everything/issues/277

### Briefly explain your program logic - 
I created a react component with useState hooks to update the placeholders. Used two libraries to convert number to words as there was no one standard library to do both Indian and International conversions.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by plon-Susk7** [comment]
hi @SarthakKeshari , I had to close the previous issue because I messed up while pulling updated code. Here's a new PR that has no conflict. Thanks :)

**Comment by SarthakKeshari** [comment]
@plon-Susk7,
Its fine that there are no merge conflicts, but kindly revert the changes in App.js and Home.js

**Comment by plon-Susk7** [comment]
Already done

**Comment by SarthakKeshari** [comment]
Kindly check the files changed section. It will show you the files that are being affected. And it show the changes made to App.js and Home.js

**Comment by plon-Susk7** [comment]
Thanks for the feedback @SarthakKeshari , I have reverted the changes.

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @plon-Susk7 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
@plon-Susk7,
I am really impressed by the consistent effort you have put in to make this merge. Kudos to your dedication. 
Adding admin-appreciation points to this PR for constant effort and dedication. 👏👏

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by plon-Susk7** [comment]
Thank you so much @SarthakKeshari, it means a lot. I starred the repo before starting to work on this issue.

**Pull request merged**
