### PR TITLE
add image to pdf consolidator 

### PR DESCRIPTION
**Pull request by tejxv**
### Issue Id you have worked upon - 
#328 

### Briefly explain your program logic - 
added image to pdf maker, select multiple images and combine them into a single PDF file.
### Screenshots(Attach 2 screenshots of your own input and output) - 

https://github.com/SarthakKeshari/calc_for_everything/assets/54097365/2e97a233-32ed-4984-8f77-e6d219b46897

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by tejxv** [comment]
@SarthakKeshari hello, is there any problem with this PR, I'm happy to resolve those, just let me know!

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@tejxv,
Your code works well. I was just doing the code review.

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @tejxv on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Pull request merged**
