### PR TITLE
Implemented Quadratic Equation Intersection Calculator (Fixes #33)

### LINKED ISSUE #33: Quadratic Eq. Intersection Calculator
### Enter calculator name - 
Quadratic Eq. Intersection Calculator

### Describe calculator functionality - 
Given two quadratic equations, find whether they will <b>intersect or not</b>, if <b>yes</b> display the intersection points. And if <b>not</b>, display - "Equations do not intersect"

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

### PR DESCRIPTION
**Pull request by DeexithParand2k2**
### Issue name and ID I worked on - 
Quadratic Equation Intersection Calculator (Issue #33)

### Briefly explain your program logic - 
1. The function takes six parameters `a1`, `b1`, `c1`, `a2`, `b2`, and `c2`, which represent the coefficients of two quadratic equations of the form `a * x^2 + b * x + c`.

2. It calculates the discriminant (`disc`) using the formula `disc = B^2 - 4 * A * C`, where:
   - `A` is the difference between `a1` and `a2`.
   - `B` is the difference between `b1` and `b2`.
   - `C` is the difference between `c1` and `c2`.

3. The code then checks three cases separately:
   - If the discriminant (`disc`) is greater than 0, it means there are two real roots for the quadratic equations.
     - It calculates the first root `x1` and its corresponding `y1` value.
     - It calculates the second root `x2` and its corresponding `y2` value.
     - It sets the `result` variable to a string indicating that the equations intersect at `[x1, y1]` and `[x2, y2]`. The `toPrecision(2)` method is used to round the values to two decimal places.

   - If the discriminant is equal to 0, it means there is only one real root for the quadratic equations.
     - It calculates the root `x` and its corresponding `y` value.
     - It sets the `result` variable to a string indicating that the equations intersect at `[x, y]`. Again, `toPrecision(2)` is used for formatting.

   - If the discriminant is less than 0, it means there are no real roots, and the equations do not intersect.
     - It sets the `result` variable to indicate that the equations do not intersect.

4. Finally, the `result` variable is updated with the appropriate message based on the calculation results, indicating whether the equations intersect and, if so, where.

## Two Real Roots use case
image

## Single Real Root use case
image

## No Real Root use case
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by DeexithParand2k2** [comment]
hi @SarthakKeshari I've completed working on the issue "Quadratic Equation Intersection Calculator" within the specified deadline. Kindly accept and merge my PR as soon as possible. Thank you so much for the opportunity.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @DeexithParand2k2 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
@DeexithParand2k2, 
The efforts you have put in not only to write your code but also explain it so well, adding admin-appreciation points for this PR.

Kudos to you!! 🎉

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by DeexithParand2k2** [comment]
Thank you @SarthakKeshari for the opportunity. Would love to contribute more. Thank you.

**Pull request merged**
