### PR TITLE
loan repayment calculator

### PR DESCRIPTION
**Pull request by Saksham-245**
### Issue Id you have worked upon - 
#61 

### Briefly explain your program logic - 
1. State Variables: The component uses React's useState hook to manage several pieces of state: principal, rate, time, monthlyPayment, totalInterest, totalAmount, and tab. These represent the principal amount, interest rate, time period, monthly payment, total interest, total amount to be repaid, and the currently selected tab, respectively.

2. calculatePayment Function: This function, wrapped in a useCallback hook for performance optimization, calculates the monthly payment, total interest, and total amount based on the current state of principal, rate, and time. It also calculates the time period based on the principal, rate, and monthlyPayment if the second tab is selected.

3. useEffect Hook: This hook is used to call the calculatePayment function whenever any of its dependencies change. This ensures that the calculated values are always up-to-date with the input values.

4. handleTabChange Function: This function is used to handle the change of tabs. It resets all the state variables when a tab is changed.

5. Rendered JSX: The component returns a container with a title, tabs for selecting the calculation mode, and inputs for entering the principal, rate, and either time or monthly payment. It also displays the calculated monthly payment, total interest, and total amount (or time, if the second tab is selected).

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
Screenshot 2023-10-04 at 1 28 37 AM
Screenshot 2023-10-04 at 1 29 22 AM
Screenshot 2023-10-04 at 1 30 03 AM
<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
Hey @Saksham-245,
I wish if you could display Total Interest Payable and Total Amount Payable fields under CALCULATE REPAYMENT PERIOD as well.

**Comment by Saksham-245** [comment]
Ok sure!

**Comment by Saksham-245** [comment]
Hi @SarthakKeshari I have made the following change that you have requested.

**Comment by Saksham-245** [comment]
Sure

**Comment by SarthakKeshari** [comment]
Looks good. Will Review the code once again and merge.

**Comment by Saksham-245** [comment]
Sure @SarthakKeshari !!

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Saksham-245 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by Saksham-245** [comment]
Sure @SarthakKeshari

**Pull request merged**
