### PR TITLE
Added MainPHCalc.js

### PR DESCRIPTION
**Pull request by Saifullah00**
### Issue Id you have worked upon - 
#71 

### Briefly explain your program logic - 
This application allows users to input a pH value, click the "Calculate pH" button, and see whether the pH is acidic, neutral, or alkaline. The pH calculation is performed in the calculatePh function, and the result is updated in the result state variable.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Screenshot 2023-10-02 1

Screenshot 2023-10-02 2

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Saifullah00 on your contribution.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by Saifullah00** [comment]
> Congratulations 🎉 @Saifullah00 on your contribution.

Thank you for the opportunity 😊

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Pull request merged**
