### PR TITLE
Implement Roman Numeral Operation Calculator

### PR DESCRIPTION
**Pull request by SakshiJSanghavi**
### Issue Id you have worked upon - 
590

### Briefly explain your program logic - 
The provided JavaScript code defines a React component for a Roman Numeral Operation Calculator. The component utilizes the useState hook to manage state variables, including the input Roman numerals (num1 and num2), the selected operation (operation), and the result of the operation (result). The main logic lies within the performOperation function, which is triggered when the user clicks the "Perform Operation" button. This function attempts to convert the input Roman numerals to Arabic numerals, performs the specified arithmetic operation, and then converts the result back to a Roman numeral. The program also handles potential errors, such as invalid Roman numerals or operations, displaying an error message if needed. The user interface is designed using Material-UI components, featuring input fields for numerals and the operation, a button to initiate the calculation, and a display area for the result. The code integrates the romanize library to facilitate the conversion between Roman and Arabic numerals, contributing to the overall functionality of the Roman Numeral Operation Calculator. State management in React ensures dynamic updates and responsiveness to user interactions.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — COMMENTED** [review]
Kindly revert all the changes in this file.

**Review by SarthakKeshari — COMMENTED** [review]
Kindly revert all the changes in this file.

**Comment by SakshiJSanghavi** [comment]
I have revert back the changes in package.json and package-lock.json that lies outside calculators folder.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @SakshiJSanghavi on your contribution.
Thanks for adding value to this repository. 😊

**Pull request merged**
