### PR TITLE
diamondProblemSolver

### PR DESCRIPTION
**Pull request by Alfred-hhy**
Issue Id: #591 

Briefly explain your program logic:
This React component is a Diamond Problem Solver. It takes two factors as input, calculates their product and sum, and displays the results. The calculations are updated whenever the input factors change. It also includes basic input validation.

Screenshots:
image
image

By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code.
- [x] My code gives the correct output.
- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Alfred-hhy,
Kindly re-read the calculation functionality description in the issue

**Comment by Alfred-hhy** [comment]
@SarthakKeshari 
Please review the modified pull request once again.
Issue Id: #612

Briefly explain your program logic:

1. State Variables: The component uses the useState hook to manage state variables for a, b, product, sum, equationSteps, and calculateButtonClicked.
2. Input Validation: The isInteger function checks if a given value is an integer using a regular expression.
3. Effect Hook: The useEffect hook is used to calculate values and update equation steps whenever there is a change in the state variables (a, b, product, sum, calculateButtonClicked).
4. Input Change Handling: The handleInputChange function is triggered on input changes. It updates the state variables based on the input type (a, b, product, sum). It also recalculates sum and product based on valid inputs.
5. Calculation Functions: The calculateValues function performs calculations based on the input values, updating the state variables and equation steps accordingly. It covers various scenarios to solve the Diamond Problem.
6. Button Click Handling: The handleCalculate function sets calculateButtonClicked to true, triggering the recalculation in the useEffect hook.
7. Equation Solving: The findNumbers function calculates values for a and b given the product and sum. It uses the quadratic formula and updates the equation steps.
8. Rendering: The component renders a UI with Material-UI components, including text fields for input, buttons to trigger actions, and a display of equation steps.

Screenshots:
image
image

By raising this PR I affirm that -

- [x]   My code follows the guidelines of this project.
- [x]   I have performed a self-review of my own code.
- [x]   I have commented my code.
- [x]   My code gives the correct output.
- [x]   I affirm that I strictly follow contributing guidelines and code of conduct.

**Comment by SarthakKeshari** [comment]
@Alfred-hhy, Amazing. I appreciate your efforts and clarity on issue solving. Adding admin-appreciation points for the dedication shown.

**Comment by SarthakKeshari** [comment]
@Alfred-hhy,
Kindly revert all package-lock.json and push the code again

**Comment by Alfred-hhy** [comment]
"Sure, I'll revert the package-lock.json and push the code again. Will keep you posted once it's done!"

**Comment by Alfred-hhy** [comment]
@SarthakKeshari 
I have'already revert all package-lock.json.

**Comment by SarthakKeshari** [comment]
@Alfred-hhy,
Good work. I can find the PR updated now.

Thankyou

**Review by SarthakKeshari — APPROVED** [review]

**Comment by Alfred-hhy** [comment]
@SarthakKeshari ，
I also recently started contributing to GitHub by making pull requests. Thank you for assigning tasks to me, responding quickly, and being understanding of the mistakes I made earlier.

 Sincerely grateful.

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Alfred-hhy on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by Alfred-hhy** [comment]
@SarthakKeshari 
 🎉 Thank you so much for the warm congratulations! I'm thrilled to be a part of this project and contribute to its growth. 😊

Absolutely,  🚀 I've already shared it with my friends and colleagues, and I'll continue to do so.

And of course, ⭐️ clicked! Your encouragement means a lot.  💪👨‍💻👩‍💻

**Comment by SarthakKeshari** [comment]
@Alfred-hhy,
Thank you so much.

**Pull request merged**
