### PR TITLE
Momentum Calculator

### PR DESCRIPTION
**Pull request by Pasqua101**
### Issue Id you have worked upon - 
Issue #531 

### Briefly explain your program logic - 
As mentioned in issue #531. I have created a momentum calculator that takes in mass (kg) and velocity (m/s) and returns a value of kg m/s for the momentum. There is also has a info file explaining the purpose of the calculator. 

Additionally, I have added this calculator to the list of currently implemented physics calculators and removed the duplicate physics header from the README.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Pasqua101,
In the readme file while adding your changes, you have removed the Physics section. Kindly revert the Readme file.

**Comment by Pasqua101** [comment]
Hi @SarthakKeshari , I only removed a duplication of the Physics section. Please look at the attached screenshot below that shows the deletion of the duplicate Physics section that opts for the one that has more of the calculators. 
image

Additionally, you can see this duplication on the current version of the README on the main page. As seen below.
image
 
The changes to made to the README address this duplication. However, if this is not what you want, I can revert this. Please let me know. Thank you.

**Comment by SarthakKeshari** [comment]
@Pasqua101,
Thanks for the help. I got your point. 😊

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@Pasqua101,
Glad to see you have updated the Info file. Appreciating your efforts by adding admin-appreciation points. 👏👏

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Pasqua101 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by Pasqua101** [comment]
Done. Thanks for accepting my PR!

**Pull request merged**
