### PR TITLE
Co-Linear Points Finder

### PR DESCRIPTION
**Pull request by aniketsinha5552**
### Briefly explain your program logic - 
The program finds out if a group of points (min:3, max:6) are co-linear or not by comparing the slope of each point with the first point.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by aniketsinha5552** [comment]
Hey, @SarthakKeshari
Can you let me know if this is what's required:
The program should give all the groups of co-linear points from the input.
Eg: Input : n=5 , points: `[ (1, 1), (2, 2), (3, 3), (4, 4), (1, 2) ]`
Output: Group 1:  `[ ( 1, 1 ), ( 2, 2 ), ( 3, 3 ), ( 4, 4 ) ]` , Group 2: `[ ( 2, 2 ), ( 3, 3 ), ( 4, 4 ) ]`

**Comment by SarthakKeshari** [comment]
@aniketsinha5552,
I want if user enters points eg - A B C D E
 
And A B C Falls on one line
And C D E fall on other line

So colinear Points group 1: A B C 
and colinear points group 2 : C D E

Thankyou.

**Comment by aniketsinha5552** [comment]
@SarthakKeshari Okay, Thank you for the clarification

**Comment by SarthakKeshari** [comment]
An amazing re-work and effort #140

**Pull request closed without merging**
