### PR TITLE
Golden Ratio Calculator

### PR DESCRIPTION
**Pull request by 1520229462**
### Issue Id you have worked upon - 
594

### Screenshots(Attach 2 screenshots of your own input and output) - 
微信截图_20231031155501

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@1520229462, Kindly go through the calculator functionality described in #594

**Comment by SarthakKeshari** [comment]
@1520229462,
Kindly revert all the package-lock.json

**Comment by 1520229462** [comment]
I've made changes to this issue based on the molarMassCalc page @SarthakKeshari

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @1520229462 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by 1520229462** [comment]
yes

**Pull request merged**
