### PR TITLE
MUX Caclulator implemented #384

### PR DESCRIPTION
**Pull request by sikehish**
[Issue ID: #384](https://github.com/SarthakKeshari/calc_for_everything/issues/384)

I've used an array to keep track of the resulting output, and an index, which basically signifies which line would be selected as the output depending on the given input string representing the select lines. My code also checks for inconsistencies and flags them to the user.

Outputs
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@sikehish,
Kindly revert package.json and package-lock.json

**Comment by sikehish** [comment]
> revert package.json and package-lock

What's the issue? Could you please explain

**Comment by SarthakKeshari** [comment]
> > revert package.json and package-lock
> 
> I have reverted to the master branch's package.json and package-lock.json.
> 
> Also, [propagation delay issue](https://github.com/SarthakKeshari/calc_for_everything/issues/396) is also solved. Ill create another PR for it once this is merged.

Sure

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @sikehish on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by sikehish** [comment]
Sure @SarthakKeshari! Thanks for the opportunity. Looking forward to more contributions and opportunities!

**Pull request merged**
