### PR TITLE
Mean Calculator Added!

### PR DESCRIPTION
**Pull request by VincentPaulV**
### Issue Id you have worked upon - 
Mean Calculator #447 

### Briefly explain your program logic - 
Okay so the crux of my program is:
1. Take the user input for the number of groups/classes
2. Generate those many rows for input
3. Take the first column as range-> Perform string operations to get the max and min of the range.
4. The second column is our count or frequency of each class
5. We take the mean of each class multiply it with frequency and summation about column to get the mean.
6. Mean is displayed on click of Calculate mean button

### Screenshots(Attach 2 screenshots of your own input and output) - 
<br>

image
<br>

image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by VincentPaulV** [comment]
Hey there @SarthakKeshari !!

Here is the PR raised for #447 
Thanks for giving me the opportunity to contribute!!

I also have a request from my end, though the concept of calculating the mean is very simple at its core, I personally believe the UI + String Operations are time-consuming, and difficult and definitely escalate this issue to being a medium-difficulty one.

If you agree to the same then could you please upgrade this issue to a medium-level difficulty, not just for the sake of the points but more of an acknowledgment of the time and effort I have put in for my contribution?

Thanks a lot!!

**Comment by VincentPaulV** [comment]
Hey there @SarthakKeshari!!
Is there any update regarding my query mentioned above?
Do let me know your thoughts on the same.

Thanks!!

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@VincentPaulV,
As the issue points are decided as per the amount of brainstorming and efforts that would be required. So, I will continue to place it in easy category only. But appreciating your efforts I am adding admin-appreciation points to the same.

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @VincentPaulV on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Pull request merged**
