### PR TITLE
Number Type Finder

### PR DESCRIPTION
**Pull request by Sk783**
### Issue Id you have worked upon - 
#255

### Briefly explain your program logic - 
This calculator aids in understanding and classifying various numbers, including Armstrong, Kaprekar, Automorphic, Perfect, Amicable, Fibonacci, Palindromic, Smith, Harshad, and Happy Numbers.

### Screenshots(Attach 2 screenshots of your own input and output) - 

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by Sk783** [comment]
@SarthakKeshari , 
as per my understanding the code written is not clean and looks quite cluttered. So i wish to retransform the code to attain modular approach.

**Comment by SarthakKeshari** [comment]
> @SarthakKeshari , as per my understanding the code written is not clean and looks quite cluttered. So i wish to retransform the code to attain modular approach.

@Sk783, 
Thanks for pointing it out. I will increase the points for this story, as this work would require an extra effort.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Sk783 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
@Sk783,
Great work. Thanks for cleaning the code base and increasing code readability.
Adding appreciation points for the efforts you have put in. 👏

**Pull request merged**
