### PR TITLE
Added Copy To Clipboard (Feature)

### PR DESCRIPTION
**Pull request by ArnabBCA**
### Issue Id 
#20 
Implemented Copy to Clipboard Using ( react-copy-to-clipboard )

### Briefly explain your program logic - 

A "Copy to Clipboard" feature is essential as it allows users to easily copy large solutions, reducing the chance of errors when manually transcribing information. This feature enhances user experience and efficiency, making it a valuable addition to this application.

I have implemented this feature in all the calculations.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
Copied

Copy to Clipboard

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
Hello @ArnabBCA,
Great to see a feature addition 🎉. 
#### Abiding by the contribution guidelines. Kindly raise an issue first.

**Comment by ArnabBCA** [comment]
Thank you for your feedback I have raised a issue regarding this :)

**Comment by SarthakKeshari** [comment]
Kindly attach issue number to the PR description.

**Comment by ArnabBCA** [comment]
Done👍

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
