### PR TITLE
Paragraph summarizer using Reactjs

### PR DESCRIPTION
**Pull request by uttkarsh1m**
### Issue Id you have worked upon - 
#327 

### Briefly explain your program logic - 
Paragraph summarizer using Reactjs takes input of atleast 5 sentences and gives the summary. 

### Screenshots(Attach 2 screenshots of your own input and output) - 
Screenshot 2023-10-18 112435
Screenshot 2023-10-18 112534

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@uttkarsh1m,
Kindly add package.js with the required dependencies

**Comment by uttkarsh1m** [comment]
@SarthakKeshari i have not used any dependency only used the logic to summarize the paragraph .

**Comment by SarthakKeshari** [comment]
@uttkarsh1m,
Thanks for confirmation.

**Review by SarthakKeshari — APPROVED** [review]

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by SarthakKeshari** [comment]
@uttkarsh1m,
A very good and clean code delivery. Adding admin-appreciation points to this PR for good logical code delivery.

**Pull request merged**
