### PR TITLE
Image Text Reader

### PR DESCRIPTION
**Pull request by divyansh-4**
### Issue Id you have worked upon - 
Image Text Reader

### Briefly explain your program logic - 
Used Tesseract JS and buffer to enable users to upload a pdf with english text and get the extracted text in a text area.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by divyansh-4** [comment]
Apologies for the mistake on my end. I have filled the form. Do let me know if there is anything else to be done or fixed in this regard.

**Comment by SarthakKeshari** [comment]
@divyansh-4,
While reviewing I came across following libraries that you have installed. May you explain the need of each of them in your code. As per my understanding many libararies installed ain't required for this code.

Libraries are as follows - 
    "buffer": "^6.0.3",
    "draft-js": "^0.11.7",
    "draftjs-to-html": "^0.9.1",
    "pdfjs-dist": "^2.16.105",
    "tesseract.js": "^2.0.0-beta.1",

**Comment by divyansh-4** [comment]
@SarthakKeshari,
Apologies. a few of those libraries are not required in this version. I had added them to experiment with the other features that I had mentioned could be added to the Image Text Reader. For this issue, we only need Tesseract, and Buffer. 
Tesseract JS essentially does the heavy lifting for Text Recognition from the Image, and Buffer, is well, the Buffer where the file is being stored to be worked upon.
I have removed the unnecessary libraries and commited as well.
Do let me know if there are any changes required from my end. Thank You !

**Comment by divyansh-4** [comment]
@SarthakKeshari 
Sorry for the confusion. I have reverted the changes. 
Do let me know if there are any changes required from my end. Thank You !

**Comment by divyansh-4** [comment]
Hi @SarthakKeshari 
Could you let me know if any other work needs to be done with this ?

**Comment by divyansh-4** [comment]
Ahh, I am really sorry, I made a mistake. I was actually creating a new PR for the other task that you had assigned to me for the satellite location and ended up making this mistake. Can I create a new issue and create the code for a PR there ?

**Pull request closed without merging**
