### PR TITLE
Create ChemicalKineticCalculator

### PR DESCRIPTION
**Pull request by Harshit-Poddar90**
Added the code in python

### Issue Id you have worked upon - 
121

### Briefly explain your program logic - 
Import React and Component: We start by importing the necessary modules, including React and the Component class. Class Definition - ChemicalKineticsCalculator: We define a class called ChemicalKineticsCalculator that extends the Component class, which is the base class for all React components. Constructor: In the constructor, we set up the initial state of the component. The state is an object that stores data and can be updated over time. In this example, we initialize various fields such as initial concentrations, time, and the results (reaction rate and rate constant). handleInputChange Method: This method handles changes in the input fields. When a user types a value into an input field, this function is called to update the corresponding state property. calculateRate Method: This method is a placeholder for the actual chemical kinetics calculations. In a real application, this is where you would perform complex calculations based on the input data and update the state with the results. Render Method: The render method is a required method for React components. It defines what the component should render on the screen. In this case, it displays a form with input fields for initial concentrations and time, a "Calculate Rate" button, and the calculated results. Input Fields: There are input fields for the initial concentrations of reactants A and B, the product, and time. Users can input their values into these fields. "Calculate Rate" Button: Clicking this button triggers the calculateRate method, which, in this example, generates random values as a placeholder for the actual chemical kinetics calculations. Displaying Results: The calculated reaction rate and rate constant are displayed below the button, but only if they are not null. In a real application, these values would be populated based on the actual calculations. This code provides the basic structure for a React app that simulates a Chemical Kinetics Calculator. However, it's essential to replace the placeholder calculations in the calculateRate method with the actual chemical kinetics calculations that suit your specific requirements and equations.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
Hey @Harshit-Poddar90,
It's a React application. Kindly add the code, as per the ReactJS application.

**Comment by Harshit-Poddar90** [comment]
@SarthakKeshari I have changed. Let me know if this works.

**Comment by SarthakKeshari** [comment]
Kindly use Material-UI

**Comment by Harshit-Poddar90** [comment]
Updated. @SarthakKeshari

**Comment by SarthakKeshari** [comment]
Amazing. Will review the code

**Comment by SarthakKeshari** [comment]
@Harshit-Poddar90,
Kindly place your code in - 
### calc_for_everything\calculators\src\chemistry\chemicalKineticsCalc\MainChemicalKineticsCalc.js

**Comment by Harshit-Poddar90** [comment]
updated @SarthakKeshari

**Comment by Harshit-Poddar90** [comment]
@SarthakKeshari Updated

**Comment by SarthakKeshari** [comment]
> @Harshit-Poddar90, Kindly place your code in -
> 
> ### calc_for_everything\calculators\src\chemistry\chemicalKineticsCalc\MainChemicalKineticsCalc.js

Kindly follow my above comment.

**Comment by Harshit-Poddar90** [comment]
@SarthakKeshari Umm like i am not able to understand. Its showing its there in the same path which you told.

**Comment by SarthakKeshari** [comment]
Hey @Harshit-Poddar90,
You have created a file named - 'MainChemicalKineticsCalculator.js' but the file that is existing in the repository has name 'MainChemicalKineticsCalc.js'. So, you need to add your code in existing file which is - 'MainChemicalKineticsCalc.js'

**Comment by SarthakKeshari** [comment]
In order to keep the issues and PRs healthy I am merging this PR and will take care of the required filename change.

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
