### PR TITLE
Added File-Data Comparator

### PR DESCRIPTION
**Pull request by rishirohilla**
### Issue Id you have worked upon - 
#281 

### Briefly explain your program logic - 
Users can input content into two text areas representing File 1 and File 2. Upon clicking "Compare," it identifies and displays the differing lines between the two files along with their respective line numbers.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@rishirohilla,
The Comparator will make it difficult for the user to understand the difference in two files. As you may see from the second screenshot. Users will have to read the complete line to understand the difference himself.

I would suggest if the UI highlights the difference in text.

**Comment by rishirohilla** [comment]
I have updated the code for PR of issue #281  , please look into it , given my best
image

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @rishirohilla on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Pull request merged**
