### PR TITLE
Added ChemicalFormulaValidator

### PR DESCRIPTION
**Pull request by sachinsingh2020**
### Issue Id you have worked upon - 
#280

### Briefly explain your program logic - 
I have made an array of all the chemicals present in chemistry and then checking the input formula is included in the array or not if it is not then it will show invalid formula, if it is there in the array then it will show valid formula

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@sachinsingh2020, What if the formula is valid but is not present in the array of chemical values?

**Comment by SarthakKeshari** [comment]
@sachinsingh2020, What if the formula is valid but is not present in the array of chemical values?

**Comment by SarthakKeshari** [comment]
@sachinsingh2020, What if the formula is valid but is not present in the array of chemical values?

**Comment by sachinsingh2020** [comment]
> @sachinsingh2020, What if the formula is valid but is not present in the array of chemical values?

I tried to add all of them, Yes maybe there is a chance of that too by the way.
I had tried to find api for validate the formula but not able to find so, that was the only way

**Comment by SarthakKeshari** [comment]
@sachinsingh2020,
A deeper understanding for chemistry needs to be applied to make the calculator work. 
Since calculator needs to evaluate the cation and anion charges in the compound.

**Comment by Ayush-Vish** [comment]
@sachinsingh2020  Can you please tell the procedure to run the application.

**Comment by sachinsingh2020** [comment]
> @sachinsingh2020 Can you please tell the procedure to run the application.

@Ayush-Vish I have made an array of all the chemicals present in chemistry and then checking the input formula is included in the array or not if it is not then it will show invalid formula, if it is there in the array then it will show valid formula

**Comment by Ayush-Vish** [comment]
> > @sachinsingh2020 Can you please tell the procedure to run the application.
> 
> @Ayush-Vish I have made an array of all the chemicals present in chemistry and then checking the input formula is included in the array or not if it is not then it will show invalid formula, if it is there in the array then it will show valid formula

No I am talking about the installation. Actually I am  getting error.

**Comment by sachinsingh2020** [comment]
clone the repo in your device 
1. cd calculators 
2. run npm install 
3. npm start

**Comment by SarthakKeshari** [comment]
@sachinsingh2020,
Merging this PR, you may raise another issue if you wish to upgrade this calculator as improvements can be done.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @sachinsingh2020 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Pull request merged**
