### PR TITLE
Added Base Change Calculator Fixes #374

### LINKED ISSUE #374: Base Change Calculator
### Enter calculator name - 
Base Change Calculator

### Describe calculator functionality - 
The Base Change Calculator takes a number N in the base n and converts it into a number M of base m. ( both being equal )
( the negative values for each may/may-not be handled )

### Under which category you wish to place it - 
- [ ] Computer Science
- [x] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Art
- [ ] Finance
- [x] Scientific
- [ ] Health
- [ ] Sports
- [x] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

### PR DESCRIPTION
**Pull request by its-kumar-yash**
### Issue Id you have worked upon - 
I have worked on issue #374 and added a base change calculator.

Fixes #374 

### Briefly explain your program logic - 
The Base Change Calculator takes the input number and input base, converts the input number to a decimal number, and then converts the decimal number to the desired output base. It uses TextField components for input, parseInt to convert to decimal, toString to convert to the output base, and Typography to display the result. 
Number Conversion: When the user clicks the "Convert" button, the handleConvert function is triggered. It first checks if all the required inputs are provided. Then, it parses the input number using the parseInt function, specifying the input base. This converts the input number from its original base to a decimal number.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @its-kumar-yash on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by its-kumar-yash** [comment]
> ### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
> image

Done ✅🌟

**Comment by SarthakKeshari** [comment]
> Done ✅🌟
Thankyou 🤩

**Pull request merged**
