### PR TITLE
Density Calculator

### PR DESCRIPTION
**Pull request by Pasqua101**
### Issue Id you have worked upon - 
Issue #346 

### Briefly explain your program logic - 
The calculator solves for density (p) of a substance, by taking in the mass (m) and volume (v) of it. Then dividing it like so p = m/v. Other than the program logic, I also included this calculator and other currently implemented physics calculators in the README file.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Pasqua101 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by SarthakKeshari** [comment]
@Pasqua101,
It's really impressive to the end-to-end code delivery 👏. Like updating the readme and info file.
Adding admin-appreciation points for the efforts and professionalism shown.

**Comment by Pasqua101** [comment]
Thanks, glad you liked it. I noticed a couple spelling and grammatical mistakes in some of the README files. I wasn't sure if I should've addressed them in this PR. I'll make an issue for them and wait for you to assign it to me.

**Pull request merged**
