### PR TITLE
added mandala creator

### PR DESCRIPTION
**Pull request by nipun221**
### Briefly explain your program logic - 
Made a simple mandala maker with 4 quadrants 

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
image
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @nipun221 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by SarthakKeshari** [comment]
@nipun221,
I appreciate you for taking up admin-choice question and completing it with such a grace. Extra points have been added to this PR for taking up such a critical calculator.
Keep it up!! 👏👏

**Comment by nipun221** [comment]
@SarthakKeshari i have another and better approach regarding mandala maker here is the reference 
https://css-tricks.com/building-a-circular-navigation-with-css-clip-paths/#:~:text=Defining%20the%20Clip%20Path%20(The,inset()%20or%20polygon()%20.

**Pull request merged**
