### PR TITLE
added decimal to binary convertor

### PR DESCRIPTION
**Pull request by abhijithhegde**
### Issue Id you have worked upon - 
#4 Decimal to binary and binary to decimal convertor

### Briefly explain your program logic - 
Parse the input taken from the user using parseInt method,
if the parsed value is a then display it 

### Screenshots(Attach 2 screenshots of your own input and output) - 
image
<br>
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@abhijithhegde,
Kindly add the issue id

**Comment by abhijithhegde** [comment]
hey, I have added it

**Comment by SarthakKeshari** [comment]
@abhijithhegde, Sure

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @abhijithhegde on your contribution.

**Pull request merged**
