### PR TITLE
Profit Margin Calculator Added

### PR DESCRIPTION
**Pull request by Heramb4270**
### Issue Id you have worked upon - 
#146

### Briefly explain your program logic - 
Developed  the UI for User to Enter companyRevenue , goodsSold , operatingExpense , interestExpense  and taxes . restricted user to not enter any other value expect number (int) after entering the details gross profit margin , operatingProfitMargin and netProfitMargin are calculated . i have used useState hook to store values entered by user and calculate the  results. along with that ,results are only displayed when the clicks on calculate profit button  and after all calculations are done doing . user can go back by clicking on back button. 

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
Screenshot from 2023-10-05 23-57-29

Screenshot from 2023-10-05 23-58-14

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Heramb4270,
Kindly revert the changes made to **App.js and Home.js**.

**Comment by Heramb4270** [comment]
@SarthakKeshari Sir No changes to App.js and Home.js (no conflict to base branch)

**Comment by SarthakKeshari** [comment]
@Heramb4270, 
Kindly head on to the Files changed section of the PR, it is showing the changes made to App.js and Home.js. You may resolve this by rolling back the changes on the above-mentioned files then taking a pull from the repository and then pushing back the changes which will update the PR.

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @ on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Pull request merged**
