### PR TITLE
added kinetic energy calculator

### PR DESCRIPTION
**Pull request by aditya962**
### Issue Id you have worked upon - 
Kinetic Energy Calculator #403

### Briefly explain your program logic - 
Created two input fields that take mass and velocity inputs and a function that calculates kinetic energy upon a button click using standard kinetic energy formula.

### Screenshots(Attach 2 screenshots of your own input and output) - 

KE_1
KE_2

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @aditya962 on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
@aditya962, 
Great to see, that you have also completed the info file too. Thanks for the responsible behaviour shown.
Adding admin-appreciation points for the appraising contribution.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by aditya962** [comment]
Thank you so much, I am delighted to share my contributions..:))

**Pull request merged**
