### PR TITLE
added comsomassconverter

### PR DESCRIPTION
**Pull request by chinmayr633**
### Issue Id you have worked upon - 
#266

### Briefly explain your program logic - 
 Converter a user-input mass value in a selected unit (e.g., kilograms,gram..etc) and converts it into another selected unit and also have a planetary weight calculator that provides you with the ability to see how your weight would vary on various planets  in our universe based on their gravitational forces.

### Screenshots(Attach 2 screenshots of your own input and output) - 
cosmo1

cosmo 2

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@chinmayr633,
As I can see from first screenshot, result should be 2000.00 grams right, instead of 2000.00 kilograms?

**Comment by chinmayr633** [comment]
oh sorry i didnt checked i will make it correct

**Comment by SarthakKeshari** [comment]
@chinmayr633,
Do let me know once its updated

**Comment by chinmayr633** [comment]
@SarthakKeshari 
I have updated it, can i push now

**Comment by SarthakKeshari** [comment]
@chinmayr633, Yes sure. Do take a pull before pushing

**Pull request closed without merging**
