### PR TITLE
[ADDED] : Day Scheduler 

### LINKED ISSUE #274: Day Scheduler
### Enter calculator name - 
Day Scheduler

### Describe calculator functionality - 
The scheduler should allow the user to plan his day and download a copy of his schedule.

### Under which category you wish to place it - 
- [ ] Computer Science
- [ ] Mathematics
- [ ] Physics
- [ ] Chemistry
- [ ] Biology
- [ ] Finance
- [ ] Scientific
- [x] Health
- [ ] Sports
- [ ] Let project owner decide
- [ ] Suggest a new category - _(Answer here)_

### PR DESCRIPTION
**Pull request by Ayush-Vish**
### Issue Id you have worked upon - 
I have worked on the issue #274  and I have added a scheduler and the functionality to download the Schedule
fixes #274 
### Briefly explain your program logic - 
I have used react state management, and JS  functionality like blob and createObjectURL

### Screenshots(Attach 2 screenshots of your own input and output) - 
I/P 
image
O/P
image

Downloaded tasks 
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by Ayush-Vish** [comment]
@SarthakKeshari, I am incredibly sorry for the delay.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
Congratulations 🎉 @Ayush-Vish on your contribution.
Thanks for adding value to this repository. 😊


Let's celebrate this fest 😃 by providing more developers 👨‍💻👩‍💻 an opportunity to contribute. Help us make this repository reach far and more by sharing this to your friends and colleagues. 
####  Your efforts can make difference.

**Comment by SarthakKeshari** [comment]
### Hey 👋, may you also encourage us by clicking the star icon on the repository main page. ⭐
image

**Comment by SarthakKeshari** [comment]
@Ayush-Vish,
Really a good job. Appreciated.

**Comment by Ayush-Vish** [comment]
@SarthakKeshari Thank you for your patience.

**Pull request merged**
