### PR TITLE
Create Polynomial_Equation_Root_Finder

### PR DESCRIPTION
**Pull request by Harshit-Poddar90**
Added the code in python

### Issue Id you have worked upon - 
148

### Briefly explain your program logic - 
The program's logic can be succinctly summarized in the following manner:

The user enters the degree of the polynomial, which is constrained to a maximum value of 7. The user furnishes coefficients for every term within the polynomial equation, commencing from the highest power and descending to the constant term. Utilizing the NumPy library, the program ascertains the roots of the polynomial equation. Subsequently, it presents the roots of the polynomial equation.

### Screenshots(Attach 2 screenshots of your own input and output) - 
image

<br>

### By raising this PR I affirm that -
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
Hey @Harshit-Poddar90,
It's a React application. Kindly add the code. As per the ReactJS application.

**Comment by Harshit-Poddar90** [comment]
@SarthakKeshari can you give me monday evening time. I am in a remote area and there are lots of issues in the network. Requesting.

**Comment by SarthakKeshari** [comment]
Sure, @Harshit-Poddar90

**Comment by Harshit-Poddar90** [comment]
Hey @SarthakKeshari I dont know why i am getting so many errors in this reactjs code. REquesting you to assign this one to someone else.

Thanks

**Comment by SarthakKeshari** [comment]
Sure

**Pull request closed without merging**
