### PR TITLE
Log and Antilog Calculator

### LINKED ISSUE #26: Log and Antilog Calculator
### Enter calculator name - 
Log and Antilog

### Describe calculator functionality - 
Get a number and the base for log/antilog operation as input from the user and display log and antilog of the number.

### Under which category you wish to place it - 
[] Computer Science
[x] Mathematics
[] Physics
[] Chemistry
[] Biology
[] Finance
[] Scientific
[] Health
[] Sports
[] Let project owner decide
[] Suggest a new category - _(Answer here)_

### PR DESCRIPTION
**Pull request by Sam-bhav-20**
fixed #26

### Log and Antilog Calculator

For any number and base it will find the log and antilog of it

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Sam-bhav-20, Kindly work on the review comments.

**Comment by SarthakKeshari** [comment]
@Sam-bhav-20, Yes tell me how may I help you.

**Comment by Sam-bhav-20** [comment]
Probably you have assign the review comment to yourself please assign it to me so that i can work on it

**Comment by SarthakKeshari** [comment]
Kindly go to file changed section.

**Comment by SarthakKeshari** [comment]
@Sam-bhav-20,
I am providing my review comments in brief here - 
Kindly revert following files package-lock.json, package.json and App.js
Secondly, follow the PR template to create PR

**Comment by Sam-bhav-20** [comment]
i acknowledge you but when starting the react server its not working due to some issues so i installed react scripts which will work on higher version then the server starts if you want i can revert back app.js

**Comment by SarthakKeshari** [comment]
@Sam-bhav-20,
Ok, sounds reasonable. You make keep the changes.
Kindly revert App.js then.

**Pull request closed without merging**
